application/urls.py
prefix = "https://betawx.yunchehome.com"

# 删除需求
url_del_demand = prefix + '/main/DelDemand'

# 用户需求列表
url_userDemand = prefix + '/demand/UserDemand'

# 推荐需求列表
url_recommand = prefix + '/Demand/getRecommendDemand'

# 需求详情
url_demandInfo = prefix + '/Demand/GetDemandInfo'

# 清理用户缓存
url_del_cache = prefix + '/Config/clearUserCache'

# 添加货源需求
url_add_goods = prefix + '/Demand/AddGoodsSupply'

# 添加车源需求
url_add_cars = prefix + '/Demand/AddCarSupply'

# 添加招商需求
url_add_business = prefix + '/Demand/AddMerchants'

# 添加车辆交易
url_add_carsell = prefix + '/Demand/AddCarTran'

# 添加其他模板需求
url_add_other = prefix + '/main/addDemand'

application/views.py
# encoding=utf-8
from flask import render_template, redirect, url_for,request
from application.models import Article
from flask import session
from flask import Blueprint
from . import db
import requests
import json
from flask import jsonify
from . import urls

# application = Blueprint('application', __name__, template_folder='templates',url_prefix='/application')
front = Blueprint('application', __name__, template_folder='templates')


@front.route('/')
def index():
    return render_template('index.html')


@front.route('/test')
def index2():
    return render_template('test.html')


@front.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        # print("telephone:{},password:{}".format(request.args.get('phone'), request.args.get('password')))
        return render_template('login.html')
    else:
        telephone = request.form.get('phone')
        password = request.form.get('password')
        print("telephone:{},password:{}".format(telephone, password))
        # return redirect(url_for('index'))
        res = {"retCode": "200", "retMsg": "登录成功！"}
        import json
        return str(json.dumps(res, ensure_ascii=False))


@front.route('/new_article', methods=['GET', 'POST'])
def new_article():
    if request.method == 'GET':
        return render_template('new_article.html')
    else:
        title = request.form.get('title')
        content = request.form.get('content')
        print(title, content)

        if title and content:
            # 增加：
            import datetime
            now = datetime.datetime.now()
            now = now.strftime("%Y-%m-%d %H:%S:%M")
            print('当前时间%s' % now)
            article1 = Article(title=title, content=content, create_time=now)
            db.session.add(article1)
            # 事务
            db.session.commit()
            # return str({"retCode": 0, "title": title, "content": content})
            return redirect(url_for('application.article_list'))
        else:
            return str({"retCode": 1001, "retMsg": '文章标题或内容不能为空', "retData": None})


@front.route('/article_list', methods=['GET'])
def article_list():
    # 查
    # select * from article where article.title='aaa';
    art_list = Article.query.filter(Article.id >= 1)
    return render_template('art_list.html', art_list=art_list)


@front.route('/question/<islogin>')
def question(islogin):
    if islogin == '1':
        return '发布问题页面'
    return redirect(url_for('login'))


@front.route('/read_data')
def read_data():
    class Person():
        def __init__(self, name, age):
            self.name = name
            self.age = age

    p = Person('miaomiao', 4)

    context = {
        'username': 'likai',
        'age': 22,
        'height': 178,
        'websites': {
            'baidu': 'www.baidu.com',
            'github': 'www.github.com'
        },
        'child': p
    }
    return render_template('read_data.html', **context)


## session

@front.route('/add_session/')
def add_session():
    session['userid'] = '8473'
    # 设置session过期时间
    session.permanent = True
    return 'add session success'


@front.route('/get_session/')
def get_session():
    userid = session.get('userid')
    if userid:
        return 'session data:%s' % userid
    return 'No session data found!'


@front.route('/delete_session/')
def delete_session():
    if session.get('userid'):
        session.pop('userid')
    return 'delete success'


@front.route('/easyui/')
def easyui():
    return render_template('easyui/easyui.html')


@front.route('/auto/')
def auto():
    return render_template('index.html')


@front.route('/model/')
def model():
    pass


@front.route('/easyui_message/')
def easyui_message():
    return render_template('easyui/messager.html')


@front.route('/easyui_panel/')
def easyui_panel():
    return render_template('easyui/easyui_panel.html')


@front.route('/boot/')
def boot():
    return render_template('boot.html')


@front.route('/suite/wx')
def suite_wx():
    return render_template('suite_wx.html')


@front.route('/suite/wx/demand/goods')
def wx_goods():
    return render_template('goods.html')


@front.route('/suite/neway')
def suite_neway():
    return render_template('suite_neway.html')


@front.route('/suite/finance')
def suite_finance():
    return render_template('suite_finance.html')


@front.route('/suite/all')
def suite_all():
    return render_template('auto.html')


@front.route('/suite/list/', methods=['GET', 'POST'])
def suite_list():
    return jsonify(
        {"total": 2, "rows": [{"id": 1001, "name": '登录流程测试', "comment": "登录相关流程测试描述", "createTime": "2010-08-30"},
                              {"id": 1002, "name": '发布流程测试', "comment": "发布相关流程测试描述", "createTime": "2010-09-01"}]})


@front.route('/suite/detail/', methods=['GET', 'POST'])
def suite_detail():
    print(request.url)
    print(request.args.get('id'))
    return jsonify({"total": 22, "rows": [
        {"id": 1, "suiteId": 2, "testName": "打开首页",
         "element": "com.android.packageinstaller:id/permission_allow_button",
         "index": "", "findType": "id"}]})


@front.route('/delDemands/', methods=['POST'])
def delDemands():
    openId = request.form.get('openId')
    print("openId:", openId)
    data_user = {
        "page": 1,
        "lon": 121.265562,
        "lat": 31.192338,
        "openId": openId
    }
    # 请求我的需求接口
    res_user = requests.post(urls.url_userDemand, json=data_user)
    res = json.loads(res_user.text)
    if res.get('retCode') == 0 and len(res['retData']['list']) > 0:
        for demand in res.get('retData').get('list'):
            # 获取需求id
            demandId = demand['demandId']
            data_del = {
                "id": demandId,
                "openId": openId
            }
            # 请求删除需求接口
            res_del = requests.post(urls.url_del_demand, json=data_del)
            if res_del.status_code != 200:
                continue
        return jsonify({"retCode": 0, "retMsg": "删除成功"})
    else:
        return jsonify({"retCode": 99, "retMsg": "没有找到需求"})


@front.route('/delCache')
def del_cache():
    uid = request.args.get('uid')
    print(uid)
    if uid:
        res = requests.get(urls.url_del_cache, {"uid": uid})
        # https://betawx.yunchehome.com/Config/clearUserCache?uid=6666
        print(res.url)
        if res.status_code == 200:
            return jsonify({"retCode": 0, "retMsg": "success"})
        return jsonify({"retCode": 98, "retMsg": res.status_code})
    else:
        return jsonify({"retCode": 99, "retMsg": "uid不能为空"})

server/views.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request, jsonify
from front import business
from front import urls

import requests, json

server = Blueprint('server', __name__, template_folder='../front/templates')


@server.route("/demand/model")
def demand_model():
    return render_template('models.html')


@server.route('/add_goods/', methods=['POST'])
def add_goods():
    """
    发布货源，并分析检查点
    :return: dict
    """
    print(request.form.get('openId'), request.form.get('goodsName'))
    data = {
        "openId": request.form.get('openId'),
        "goodsName": request.form.get('goodsName'),
        "startAddress": request.form.get('startAddress'),
        "endAddress": request.form.get('endAddress'),
        "carryGoodsTime": request.form.get('carryGoodsTime'),
        "carryVolume": request.form.get('carryVolume'),
        "carModel": request.form.get('carModel'),
        "addr": request.form.get('addr'),
        "endDate": request.form.get('endDate')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_goods, json=data)  # {"retCode":0,"retMsg":"","retData":{"id":"3044"}}
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1
                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            else:  # 发布需求时，retCode!=0 的情况
                return jsonify(
                    {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})
        else:  # 接口请求失败
            return jsonify({"retCode": 90, "retMsg": "请求过程中出现异常", "retData": None})

    except Exception as e:  # 其他异常
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addCars', methods=["get", "post"])
def add_cars():
    data = {
        "openId": request.form.get('openId'),
        "lineData": "[{'from':'南京市','to':'北京市'}]",
        "carNum": request.form.get('carNum'),
        "carModel": "7.6米 公路货车",
        "carryWeight": "10",
        "carryVolume": "40",
        "addr": "上海市青浦区徐德路",
        "lon": 121.265562,
        "lat": 31.192338,
        "endDate": "2018-10-01",
        "contractType": 2,
        "desc": "这里是承运介绍",
        "carImg": "https://wxcx.yunchehome.com/mpw1536216548885.jpg",
        "carPersonImg": "https://wxcx.yunchehome.com/mpw1536216554920.jpg"
    }

    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_cars, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addBusiness', methods=["get", "post"])
def add_business():
    data = {
        "openId": request.form.get('openId'),
        "companyName": request.form.get('companyName'),
        "merchantsTitle": request.form.get('merchantsTitle'),
        "merchantsArea": "[{\"prov\":\"上海市\",\"city\":\"全域\",\"area\":\"全域\"}]",
        "merchantsStartTime": 1546300800,
        "merchantsEndTime": 1551398400,
        "merchantsType": 2,
        "merchantsTypeTwo": 1,
        "merchantsCharge": request.form.get('merchantsCharge'),
        "phone": request.form.get('phone'),
        "addr": "上海市青浦区华徐公路683号",
        "lon": 121.26601,
        "lat": 31.196965,
        "endDate": "2020-10-01",
        "qualRequire": "【招商】自动发布脚本中的补充说明",
        "businessLicenseImg": request.form.get('businessLicenseImg'),
        "chargeCardImg": request.form.get('chargeCardImg'),
        "url": request.form.get('url')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_business, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addCarSell', methods=["get", "post"])
def add_carsell():
    data = {
        "openId": request.form.get('openId'),
        "addr": "上海市青浦区华徐公路683号",
        "lon": 121.26601,
        "lat": 31.196965,
        "endDate": "2018-10-10",
        "carSort": request.form.get('carSort'),
        "driveForm": 9,
        "carBrandsId": "39",
        "carSeriesId": "46",
        "maxPower": "300",
        "emissionStand": request.form.get('emissionStand'),
        "drivingLiceDate": "",
        "kilometers": "",
        "shellPrice": request.form.get('shellPrice'),
        "carImg": request.form.get('carImg'),
        "drivingRoomImg": request.form.get('drivingRoomImg'),
        "chassisImg": request.form.get('chassisImg'),
        "desc": request.form.get('desc')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_carsell, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                print("验证需求详情！")
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addOtherDemand', methods=["get", "post"])
def add_other():
    print("openId:%s" % request.get_json(force=True)['openId'])
    print(request.get_json(force=True)['info']['type'])
    print(type(request.get_json(force=True)['info']))
    data = {
        "openId": request.get_json(force=True)['openId'],
        "info": json.dumps(request.get_json(force=True)['info'])
    }

    # data = {
    #     "openId": request.get_json(force=True)['openId'],
    #     "info": {

application/templates/art_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Success</p>



<div class="easyui-panel" title="文章列表" style="width:400px;padding:10px 10px">

    <ul>
        {% for art in art_list %}
        <li>   <p>文章标题：{{ art.title }}</p>  </li>
        <li>   <p>文章内容：{{ art.content }}</p> </li>
        <hr>
        {% endfor %}
    </ul>

</div>

</body>
</html>

application/templates/auto.html
{% extends "base.html" %}

{% block body %}

    <div style="padding: 10px;">

        <table id="mytb" title="测试集合" style="width:1000px;height:500px" data-options="rownumbers:true">
        </table>
    </div>


    {#    <div id="win" class="easyui-window" title="详情" closed="true" style="width:770px;height:700px;"#}
    {#         data-options="modal:true ">#}
    {#        <p>测试流程步骤</p>#}
    {#        <table id="tb_detail" width="750px" height="600px"></table>#}
    {#    </div>#}

    {#  添加窗口  #}
    <div id="add_div" style="display: none">
        <form id="my-form">
            <p>用例名称：<input type="text" value="" placeholder="请输入"/></p>
            <p>用例名称：<input type="text" value="" placeholder="请输入"/></p>
            <p>用例名称：<input type="text" value="" placeholder="请输入"/></p>
            <p>用例名称：<input type="text" value="" placeholder="请输入"/></p>
            <p>用例名称：<input type="text" value="" placeholder="请输入"/></p>

            <a id="btn-ok" class="easyui-linkbutton">确定</a>
        </form>
    </div>


    <script type="text/javascript">


        function Edit(index) {
            alert(index)
            {#console.log(val)#}
            {#console.log(row.id)#}
            {#console.log(index)#}
            {#return '<a onclick="suiteDetail(' + row.id + ')" class="easyui-linkbutton" >查看详情</a>';#}
            {#return '<a class="btn-check" onclick="suiteDetail(' + index + ')"  >修改</a>';#}
        }

        $(function () {
            $('#mytb').datagrid({
                idField: "id",
                iconCls: 'icon-edit',  //图标
                border: true,  //表格是否显示边框
                fitColumns: true,
                {#fit:true,#}
                url: "{{ url_for('application.suite_list') }}",
                method: "get",
                scrollbarSize: 0,
                columns: [[
                    {
                        field: 'id', title: 'ID', width: 100, formatter: function (value, row, index) {
                            console.log("value:" + value) // 当前列的值
                            console.log("row:" + row.name) // 当前行的所有数据
                            console.log("index:" + index)
                            if (index % 2 == 0) { // 偶数行
                                return "<span style='color:red'>" + row.id + "</span>";
                            } else
                                return row.id
                        }
                    },
                    {field: 'name', title: '用例名称', width: 100},
                    {field: 'comment', title: '用例描述', width: 200},
                    {field: 'createTime', title: '创建时间', width: 100},
                    {
                        field: 'view', title: '操作', width: 100, formatter: function (value, row, index) {
                            console.log("index:" + index)
                            console.log("id:" + row.id)
                            var Action = "<a href='javascript:void(0);' onclick='Edit(" + index + ")'>修改</a> <a href='javascript:void(0);' onclick='Delete(" + row.ID + ")'>删除</a>";
                            return Action;
                        }
                    }
                ]],
                pagination: true,//底部是否显示分页组件
                pageSize: 5,   //表格中每页显示的行数
                pageList: [5, 10, 15],
                rownumbers: true,   //是否显示行号
                singleSelect: true, // 只能单选
                nowrap: false,
                striped: true,  //奇偶行是否使用不同的颜色
                loadMsg: '数据正在努力加载，请耐心等待...',   //加载数据时显示提示信息
                frozenColumns: [[  //固定在表格左侧的栏
                    {field: 'ck', checkbox: true},
                ]],

                toolbar: [{
                    iconCls: 'icon-add',
                    text: '添加',
                    handler: function () { // 当点击添加时，执行handler代码
                        $('#add_div').window({
                            title: "添加",
                            width: 500,
                            height: 300,
                            resizable: false,
                            minimizable: false,
                            collapsible: false,
                            maximizable: false,
                            modal: true
                        })
                        {#                        $.messager.show({
                                                    title: "添加提示",
                                                    msg: "成功添加一条记录",
                                                    timeout: 3000,
                                                    showType: "slide"
                                                })#}
                    }
                }, '-', {
                    iconCls: 'icon-edit',
                    text: '编辑',
                    handler: function () {
                        alert('编辑按钮')
                    }
                }, '-', {
                    iconCls: 'icon-remove',
                    text: '删除',
                    handler: function () {
                        alert('编辑按钮')
                    }
                }]

            });


            $('#tb_detail').datagrid({
                iconCls: 'icon-edit',  //图标
                border: true,  //表格是否显示边框
                columns: [[
                    {field: 'id', title: 'ID', width: 50, hidden: false},
                    {field: 'testName', title: '步骤名称', width: 100},
                    {field: 'element', title: '元素', width: 300},
                    {field: 'index', title: '索引', width: 50},
                    {field: 'findType', title: '查找方式', width: 100},
                    {field: 'operateType', title: '操作方式', width: 80},
                    {field: 'checkType', title: '断言方式', width: 100},
                    {field: 'checkExp', title: '预期结果', width: 100},
                ]],
                nowrap: false,
                striped: true,  //奇偶行是否使用不同的颜色
                loadMsg: '数据正在努力加载，请稍后...',  //加载数据时显示提示信息
            });


            function suiteDetail(rowId) {
                alert("detail")
                $.ajax({
                    type: 'post',
                    url: "{{ url_for('application.suite_detail') }}",
                    data: {"id": rowId},
                    dataType: 'json',
                    success: function (data) {
                        $('#win').window('open');  // open a window
                        $('#tb_detail').datagrid("loadData", data)
                    },
                    error: function (data) {
                        alert('请求流程详情失败')
                    }
                })
            }

            {#  点击：确定  #}
            $('#btn-ok').click(function () {
                $.ajax({
                    url: "{{ url_for('application.suite_detail') }}",
                    type: "post",
                    data: $('#my-form').serialize(),
                    dataType: "json",
                    success: function (result) {
                        alert("点击确定")
                        $('#add_div').hide()
                    }
                })
            })


        })
    </script>

{% endblock %}

application/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    {# 引入easyui #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    {#  引入自定义的css文件  #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='mycss.css') }}">

    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>
</head>

<body class="easyui-layout">
<div data-options="region:'north',border:false" ;
     style="height: 50px; background: #23d7ea; padding: 10px">
    <img src="{{ url_for('static',filename='images/logo.png') }}" width="100px" height="20px"/> 自动化测试平台
</div>

<div data-options="region:'west',split:true" style="width: 170px;">
    <div class="easyui-accordion" data-options="fit:true,border:false">
        <div title="测试管理" data-options="selected:true">
            <div style="margin: 5px">
                <ul class="tree easyui-tree" data-options="animate:true,lines:true" id="tt">
                    <li data-options="iconCls:'icon-group'">
                        <span>自动化测试</span>
                        <ul>
                            <li data-options="iconCls:'icon-group_add'" id="wx">
                                <span id="ww">小程序</span>
                            </li>
                            <li data-options="iconCls:'icon-group_delete'" id="neway">
                                <span>雷励金科</span>
                            </li>
                            <li data-options="iconCls:'icon-group_edit'" id="finance">
                                <span>业务系统</span>
                            </li>
                            <li data-options="iconCls:'icon-group_edit'" id="all">
                                <span>集成测试</span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        {#        <div title="数据展示" style="padding: 10px;">#}
        {#            content2#}
        {#        </div>#}
    </div>
</div>

<div data-options="region:'center'">
    {# fit：自适应父容器大小   #}
    <div id="tabs" class="easyui-tabs" data-options="tools:'#tab-tools',fit:true">
        <div title="主页" data-options="iconCls:'icon-house'" style="padding: 20px">
            <p>欢迎使用自动化测试平台</p>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $('#tt').tree({

            onClick: function (node) {
                if ($('#tabs').tree('isLeaf', node.target)) { //判断是否是叶子节点
                    {#var tab = $('#tt').tabs('getSelected');#}
                    if ('wx' == node.id) {
                        addTabs(node.text, "{{ url_for('application.suite_wx') }}")
                    } else if ('neway' == node.id) {
                        addTabs(node.text, "{{ url_for('application.suite_neway') }}")
                    } else if ('finance' == node.id) {
                        addTabs(node.text, "{{ url_for('application.suite_finance') }}")
                    } else {
                        addTabs(node.text, "{{ url_for('application.suite_all') }}")
                    }
                }
            }
        })


        //生成新的选项卡
        function addTabs(text, url) {

            //若选项卡已存在，则选中该选项卡
            if ($("#tabs").tabs('exists', text)) {
                $("#tabs").tabs('select', text);
            } else {
                $("#tabs").tabs('add', {
                    title: text,
                    closable: true,
                    href: url,
                });
            }
        }
    })


</script>
</body>
</html>

application/templates/new_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>
</head>
<body>

<div class="easyui-panel" title="发布文章" style="width:100%;max-width:400px;padding:30px 60px;">


    <form id="ff" method="post" ,action="{{ url_for('application.new_article') }}">

        <div style="margin-bottom:20px">
            <input name="title" type="text" style="width:100%;height: 25px" placeholder="请填写文章标题">
        </div>

        <div style="margin-bottom:20px">
            <input name="content" type="text" style="width:100%;height: 25px" placeholder="请填写文章内容">
        </div>
        <div style="margin-bottom:20px">
            <input class="easyui-linkbutton" value="立即发布" type="submit" style="width:80px"></input>
        </div>

    </form>

</div>

</body>
</html>

application/templates/test.html
{% extends "base.html" %}

{% block body %}
    <p>这是首页的数据</p>
    <div class="easyui-panel" title="测试专用" style="width:400px;padding:10px 10px">

        <p><a href="{{ url_for('application.login') }}" style="margin-bottom:20px">打开登录页面</a></p>

        <p><a href="{{ url_for('application.question',islogin=1) }}" style="margin-bottom:20px">打开问答页面</a></p>

        <p><a href="{{ url_for('application.read_data') }}" style="margin-bottom:20px">测试读取数据</a></p>

        <p><a href="{{ url_for('application.new_article') }}" style="margin-bottom:20px">发布文章</a></p>

        <p><a href="{{ url_for('application.article_list') }}" style="margin-bottom:20px">文章列表</a></p>

        <p><a href="{{ url_for('application.add_session') }}" style="margin-bottom:20px">设置session数据</a></p>

        <p><a href="{{ url_for('application.get_session') }}" style="margin-bottom:20px">读取session数据</a></p>

        <p><a href="{{ url_for('application.delete_session') }}" style="margin-bottom:20px">删除session数据</a></p>

        <p><a href="{{ url_for('application.easyui') }}" style="margin-bottom:20px">测试EasyUi用法</a></p>

        <p><a href="{{ url_for('application.boot') }}" style="margin-bottom:20px">Bootstrap4</a></p>

        <p><a href="{{ url_for('application.auto') }}" style="margin-bottom:20px">测试平台</a></p>

    </div>

{% endblock %}