application/urls.py
prefix = "https://betawx.yunchehome.com"

# 删除需求
url_del_demand = prefix + '/main/DelDemand'

# 用户需求列表
url_userDemand = prefix + '/demand/UserDemand'

# 推荐需求列表
url_recommand = prefix + '/Demand/getRecommendDemand'

# 需求详情
url_demandInfo = prefix + '/Demand/GetDemandInfo'

# 清理用户缓存
url_del_cache = prefix + '/Config/clearUserCache'

# 添加货源需求
url_add_goods = prefix + '/Demand/AddGoodsSupply'

# 添加车源需求
url_add_cars = prefix + '/Demand/AddCarSupply'

# 添加招商需求
url_add_business = prefix + '/Demand/AddMerchants'

# 添加车辆交易
url_add_carsell = prefix + '/Demand/AddCarTran'

# 添加其他模板需求
url_add_other = prefix + '/main/addDemand'

application/models.py
#encoding: utf-8

from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash



from datetime import datetime
from . import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# class User(db.Model, UserMixin):
#     id = db.Column(db.Integer, primary_key=True)
#     username = db.Column(db.String(20), unique=True, nullable=False)
#     email = db.Column(db.String(120), unique=True, nullable=False)
#     image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
#     password = db.Column(db.String(60), nullable=False)
#     posts = db.relationship('Post', backref='author', lazy=True)
#
#     def __repr__(self):
#         return f"User('{self.username}', '{self.email}', '{self.image_file}')"


# article表：
# create table article (
#     id int primary key autoincrement,
#     title varchar(100) not null,
#     content text not null,
# )

class Article(db.Model):
    __tablename__ = 'article'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.Text, nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.String,nullable=False)


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    telephone = db.Column(db.String(11),nullable=False)
    username = db.Column(db.String(50),nullable=False)
    password = db.Column(db.String(100),nullable=False)

    def __init__(self,*args,**kwargs):
        telephone = kwargs.get('telephone')
        username = kwargs.get('username')
        password = kwargs.get('password')

        self.telephone = telephone
        self.username = username
        self.password = generate_password_hash(password)

    def check_password(self,raw_password):
        result = check_password_hash(self.password,raw_password)
        return result


class Question(db.Model):
    __tablename__ = 'question'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    title = db.Column(db.String(100),nullable=False)
    content = db.Column(db.Text,nullable=False)
    # now()获取的是服务器第一次运行的时间
    # now就是每次创建一个模型的时候，都获取当前的时间
    create_time = db.Column(db.DateTime,default=datetime.now)
    author_id = db.Column(db.Integer,db.ForeignKey('user.id'))
    author = db.relationship('User',backref=db.backref('questions'))


class Answer(db.Model):
    __tablename__ = 'answer'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text,nullable=False)
    create_time = db.Column(db.DateTime,default=datetime.now)
    question_id = db.Column(db.Integer,db.ForeignKey('question.id'))
    author_id = db.Column(db.Integer,db.ForeignKey('user.id'))
    question = db.relationship('Question',backref=db.backref('answers',order_by=id.desc()))
    author = db.relationship('User',backref=db.backref('answers'))

application/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from .models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    # email = StringField('Email',
    #                     validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

application/views.py
# encoding=utf-8
from flask import render_template, redirect, url_for,request
from application.models import Article
from flask import session
from flask import Blueprint
from . import db
import requests
import json
from flask import jsonify
from . import urls

# application = Blueprint('application', __name__, template_folder='templates',url_prefix='/application')
front = Blueprint('application', __name__, template_folder='templates')


@front.route('/')
def index():
    return render_template('index.html')


@front.route('/test')
def index2():
    return render_template('test.html')


@front.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        # print("telephone:{},password:{}".format(request.args.get('phone'), request.args.get('password')))
        return render_template('login.html')
    else:
        telephone = request.form.get('phone')
        password = request.form.get('password')
        print("telephone:{},password:{}".format(telephone, password))
        # return redirect(url_for('index'))
        res = {"retCode": "200", "retMsg": "登录成功！"}
        import json
        return str(json.dumps(res, ensure_ascii=False))


@front.route('/new_article', methods=['GET', 'POST'])
def new_article():
    if request.method == 'GET':
        return render_template('new_article.html')
    else:
        title = request.form.get('title')
        content = request.form.get('content')
        print(title, content)

        if title and content:
            # 增加：
            import datetime
            now = datetime.datetime.now()
            now = now.strftime("%Y-%m-%d %H:%S:%M")
            print('当前时间%s' % now)
            article1 = Article(title=title, content=content, create_time=now)
            db.session.add(article1)
            # 事务
            db.session.commit()
            # return str({"retCode": 0, "title": title, "content": content})
            return redirect(url_for('application.article_list'))
        else:
            return str({"retCode": 1001, "retMsg": '文章标题或内容不能为空', "retData": None})


@front.route('/article_list', methods=['GET'])
def article_list():
    # 查
    # select * from article where article.title='aaa';
    art_list = Article.query.filter(Article.id >= 1)
    return render_template('art_list.html', art_list=art_list)


@front.route('/question/<islogin>')
def question(islogin):
    if islogin == '1':
        return '发布问题页面'
    return redirect(url_for('login'))


@front.route('/read_data')
def read_data():
    class Person():
        def __init__(self, name, age):
            self.name = name
            self.age = age

    p = Person('miaomiao', 4)

    context = {
        'username': 'likai',
        'age': 22,
        'height': 178,
        'websites': {
            'baidu': 'www.baidu.com',
            'github': 'www.github.com'
        },
        'child': p
    }
    return render_template('read_data.html', **context)


## session

@front.route('/add_session/')
def add_session():
    session['userid'] = '8473'
    # 设置session过期时间
    session.permanent = True
    return 'add session success'


@front.route('/get_session/')
def get_session():
    userid = session.get('userid')
    if userid:
        return 'session data:%s' % userid
    return 'No session data found!'


@front.route('/delete_session/')
def delete_session():
    if session.get('userid'):
        session.pop('userid')
    return 'delete success'


@front.route('/easyui/')
def easyui():
    return render_template('easyui/easyui.html')


@front.route('/auto/')
def auto():
    return render_template('index.html')


@front.route('/model/')
def model():
    pass


@front.route('/easyui_message/')
def easyui_message():
    return render_template('easyui/messager.html')


@front.route('/easyui_panel/')
def easyui_panel():
    return render_template('easyui/easyui_panel.html')


@front.route('/boot/')
def boot():
    return render_template('boot.html')


@front.route('/suite/wx')
def suite_wx():
    return render_template('suite_wx.html')


@front.route('/suite/wx/demand/goods')
def wx_goods():
    return render_template('goods.html')


@front.route('/suite/neway')
def suite_neway():
    return render_template('suite_neway.html')


@front.route('/suite/finance')
def suite_finance():
    return render_template('suite_finance.html')


@front.route('/suite/all')
def suite_all():
    return render_template('auto.html')


@front.route('/suite/list/', methods=['GET', 'POST'])
def suite_list():
    return jsonify(
        {"total": 2, "rows": [{"id": 1001, "name": '登录流程测试', "comment": "登录相关流程测试描述", "createTime": "2010-08-30"},
                              {"id": 1002, "name": '发布流程测试', "comment": "发布相关流程测试描述", "createTime": "2010-09-01"}]})


@front.route('/suite/detail/', methods=['GET', 'POST'])
def suite_detail():
    print(request.url)
    print(request.args.get('id'))
    return jsonify({"total": 22, "rows": [
        {"id": 1, "suiteId": 2, "testName": "打开首页",
         "element": "com.android.packageinstaller:id/permission_allow_button",
         "index": "", "findType": "id"}]})


@front.route('/delDemands/', methods=['POST'])
def delDemands():
    openId = request.form.get('openId')
    print("openId:", openId)
    data_user = {
        "page": 1,
        "lon": 121.265562,
        "lat": 31.192338,
        "openId": openId
    }
    # 请求我的需求接口
    res_user = requests.post(urls.url_userDemand, json=data_user)
    res = json.loads(res_user.text)
    if res.get('retCode') == 0 and len(res['retData']['list']) > 0:
        for demand in res.get('retData').get('list'):
            # 获取需求id
            demandId = demand['demandId']
            data_del = {
                "id": demandId,
                "openId": openId
            }
            # 请求删除需求接口
            res_del = requests.post(urls.url_del_demand, json=data_del)
            if res_del.status_code != 200:
                continue
        return jsonify({"retCode": 0, "retMsg": "删除成功"})
    else:
        return jsonify({"retCode": 99, "retMsg": "没有找到需求"})


@front.route('/delCache')
def del_cache():
    uid = request.args.get('uid')
    print(uid)
    if uid:
        res = requests.get(urls.url_del_cache, {"uid": uid})
        # https://betawx.yunchehome.com/Config/clearUserCache?uid=6666
        print(res.url)
        if res.status_code == 200:
            return jsonify({"retCode": 0, "retMsg": "success"})
        return jsonify({"retCode": 98, "retMsg": res.status_code})
    else:
        return jsonify({"retCode": 99, "retMsg": "uid不能为空"})

application/templates/easyui/easyui.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {# 引入easyui #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>



</head>
<body>

<h1>HHHHH</h1>

<div class="easyui-panel" title="测试专用" style="width:400px;padding:10px 10px">

    <p><a href="{{ url_for('application.easyui_message') }}" style="margin-bottom:20px">消息窗体</a></p>
    <p><a href="{{ url_for('application.easyui_panel') }}" style="margin-bottom:20px">面板</a></p>

</div>

</body>
</html>

application/templates/easyui/easyui_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>


{#    2. 创建面板程序,让我们创建面板右上角的的工具栏。#}
    <script>
        $(function () {
            $('#mypanel').panel({
                width: 500,
                height: 150,
                title: 'My Panel',
                tools: [{
                    iconCls: 'icon-add',
                    handler: function () {
                        alert('new')
                    }
                }, {
                    iconCls: 'icon-save',
                    handler: function () {
                        alert('save')
                    }
                }]
            });
        })

    </script>


</head>
<body>

{#1. 通过标签创建面板,通过标签创建更简单。添加'easyui-panel'类ID到<div/>标签。#}
{#<div id="p" class="easyui-panel" title="My Panel"
     style="width:500px;height:200px;padding:10px;background:#fafafa;"
     data-options="iconCls:'icon-edit',closable:true,
                collapsible:true,minimizable:true,maximizable:true">
    <p>panel content.</p>
    <p>panel content.</p>
</div>#}

<div id="mypanel" style="padding:10px;">
    <p>panel content.</p>
    <p>panel content.</p>
</div>


</body>
</html>

application/templates/easyui/messager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>


    <script>

        {#        $(function () {
                    $.messager.alert('提示信息', '这是提示的内容，测试jquery使用')
                })#}

        {#        $(function () {
                    $.messager.confirm('确认', '您确认想要删除记录吗？', function (r) {
                        if (r) {
                            alert('确认删除');
                        } else {
                            alert('取消删除')
                        }
                    });
                })#}


        {#        $(function () {
                    $.messager.show({
                        title: '我的消息',
                        msg: '消息将在2秒后关闭。',
                        timeout: 2000,
                        showType: 'slide'
                    });
                })#}


        {#        $(function () {
                    $.messager.prompt('提示信息', '请输入你的姓名：', function (r) {

                        if (r) {
                            alert('你的姓名是：' + r);
                        }else {
                            alert('点击了取消，我什么都不用处理，自动关闭窗口')
                        }
                    });
                })#}

        $(function () {
            $.messager.progress({

                title: '这是标题',
                msg: '这是文本',
                text: '努力中...',
                interval: '500'
            });
        })


    </script>
</head>
<body>

</body>
</html>