application/urls.py
prefix = "https://betawx.yunchehome.com"

# 删除需求
url_del_demand = prefix + '/main/DelDemand'

# 用户需求列表
url_userDemand = prefix + '/demand/UserDemand'

# 推荐需求列表
url_recommand = prefix + '/Demand/getRecommendDemand'

# 需求详情
url_demandInfo = prefix + '/Demand/GetDemandInfo'

# 清理用户缓存
url_del_cache = prefix + '/Config/clearUserCache'

# 添加货源需求
url_add_goods = prefix + '/Demand/AddGoodsSupply'

# 添加车源需求
url_add_cars = prefix + '/Demand/AddCarSupply'

# 添加招商需求
url_add_business = prefix + '/Demand/AddMerchants'

# 添加车辆交易
url_add_carsell = prefix + '/Demand/AddCarTran'

# 添加其他模板需求
url_add_other = prefix + '/main/addDemand'

front/views.py
# encoding=utf-8
from flask import request
from flask import render_template, redirect, url_for
from front.models import Article
from flask import session
from flask import Blueprint
from . import db
from .models import User
import requests
import json
from flask import jsonify
from . import business, urls

# front = Blueprint('front', __name__, template_folder='templates',url_prefix='/front')
front = Blueprint('front', __name__, template_folder='templates')


@front.route('/')
def index():
    return render_template('index.html')


@front.route('/test')
def index2():
    return render_template('test.html')


@front.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('front.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)


@front.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        # print("telephone:{},password:{}".format(request.args.get('phone'), request.args.get('password')))
        return render_template('login.html')
    else:
        telephone = request.form.get('phone')
        password = request.form.get('password')
        print("telephone:{},password:{}".format(telephone, password))
        # return redirect(url_for('index'))
        res = {"retCode": "200", "retMsg": "登录成功！"}
        import json
        return str(json.dumps(res, ensure_ascii=False))


@front.route('/new_article', methods=['GET', 'POST'])
def new_article():
    if request.method == 'GET':
        return render_template('new_article.html')
    else:
        title = request.form.get('title')
        content = request.form.get('content')
        print(title, content)

        if title and content:
            # 增加：
            import datetime
            now = datetime.datetime.now()
            now = now.strftime("%Y-%m-%d %H:%S:%M")
            print('当前时间%s' % now)
            article1 = Article(title=title, content=content, create_time=now)
            db.session.add(article1)
            # 事务
            db.session.commit()
            # return str({"retCode": 0, "title": title, "content": content})
            return redirect(url_for('front.article_list'))
        else:
            return str({"retCode": 1001, "retMsg": '文章标题或内容不能为空', "retData": None})


@front.route('/article_list', methods=['GET'])
def article_list():
    # 查
    # select * from article where article.title='aaa';
    art_list = Article.query.filter(Article.id >= 1)
    return render_template('art_list.html', art_list=art_list)


@front.route('/question/<islogin>')
def question(islogin):
    if islogin == '1':
        return '发布问题页面'
    return redirect(url_for('login'))


@front.route('/read_data')
def read_data():
    class Person():
        def __init__(self, name, age):
            self.name = name
            self.age = age

    p = Person('miaomiao', 4)

    context = {
        'username': 'likai',
        'age': 22,
        'height': 178,
        'websites': {
            'baidu': 'www.baidu.com',
            'github': 'www.github.com'
        },
        'child': p
    }
    return render_template('read_data.html', **context)


## session

@front.route('/add_session/')
def add_session():
    session['userid'] = '8473'
    # 设置session过期时间
    session.permanent = True
    return 'add session success'


@front.route('/get_session/')
def get_session():
    userid = session.get('userid')
    if userid:
        return 'session data:%s' % userid
    return 'No session data found!'


@front.route('/delete_session/')
def delete_session():
    if session.get('userid'):
        session.pop('userid')
    return 'delete success'


@front.route('/easyui/')
def easyui():
    return render_template('easyui/easyui.html')


@front.route('/auto/')
def auto():
    return render_template('index.html')


@front.route('/model/')
def model():
    pass


@front.route('/easyui_message/')
def easyui_message():
    return render_template('easyui/messager.html')


@front.route('/easyui_panel/')
def easyui_panel():
    return render_template('easyui/easyui_panel.html')


@front.route('/boot/')
def boot():
    return render_template('boot.html')


@front.route('/suite/wx')
def suite_wx():
    return render_template('suite_wx.html')


@front.route('/suite/wx/demand/goods')
def wx_goods():
    return render_template('goods.html')


@front.route('/suite/neway')
def suite_neway():
    return render_template('suite_neway.html')


@front.route('/suite/finance')
def suite_finance():
    return render_template('suite_finance.html')


@front.route('/suite/all')
def suite_all():
    return render_template('suite_all.html')


@front.route('/suite/list/', methods=['GET', 'POST'])
def suite_list():
    return jsonify(
        {"total": 2, "rows": [{"id": 1001, "name": '登录流程测试', "comment": "登录相关流程测试描述", "createTime": "2010-08-30"},
                              {"id": 1002, "name": '发布流程测试', "comment": "发布相关流程测试描述", "createTime": "2010-09-01"}]})


@front.route('/suite/detail/', methods=['GET', 'POST'])
def suite_detail():
    print(request.url)
    print(request.args.get('id'))
    return jsonify({"total": 22, "rows": [
        {"id": 1, "suiteId": 2, "testName": "打开首页",
         "element": "com.android.packageinstaller:id/permission_allow_button",
         "index": "", "findType": "id"}]})


@front.route('/delDemands/', methods=['POST'])
def delDemands():
    openId = request.form.get('openId')
    print("openId:", openId)
    data_user = {
        "page": 1,
        "lon": 121.265562,
        "lat": 31.192338,
        "openId": openId
    }
    # 请求我的需求接口
    res_user = requests.post(urls.url_userDemand, json=data_user)
    res = json.loads(res_user.text)
    if res.get('retCode') == 0 and len(res['retData']['list']) > 0:
        for demand in res.get('retData').get('list'):
            # 获取需求id
            demandId = demand['demandId']
            data_del = {
                "id": demandId,
                "openId": openId
            }
            # 请求删除需求接口
            res_del = requests.post(urls.url_del_demand, json=data_del)
            if res_del.status_code != 200:
                continue
        return jsonify({"retCode": 0, "retMsg": "删除成功"})
    else:
        return jsonify({"retCode": 99, "retMsg": "没有找到需求"})


@front.route('/delCache')
def del_cache():
    uid = request.args.get('uid')
    print(uid)
    if uid:
        res = requests.get(urls.url_del_cache, {"uid": uid})
        # https://betawx.yunchehome.com/Config/clearUserCache?uid=6666
        print(res.url)
        if res.status_code == 200:
            return jsonify({"retCode": 0, "retMsg": "success"})
        return jsonify({"retCode": 98, "retMsg": res.status_code})
    else:
        return jsonify({"retCode": 99, "retMsg": "uid不能为空"})

server/views.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request, jsonify
from front import business
from front import urls

import requests, json

server = Blueprint('server', __name__, template_folder='../front/templates')


@server.route("/demand/model")
def demand_model():
    return render_template('models.html')


@server.route('/add_goods/', methods=['POST'])
def add_goods():
    """
    发布货源，并分析检查点
    :return: dict
    """
    print(request.form.get('openId'), request.form.get('goodsName'))
    data = {
        "openId": request.form.get('openId'),
        "goodsName": request.form.get('goodsName'),
        "startAddress": request.form.get('startAddress'),
        "endAddress": request.form.get('endAddress'),
        "carryGoodsTime": request.form.get('carryGoodsTime'),
        "carryVolume": request.form.get('carryVolume'),
        "carModel": request.form.get('carModel'),
        "addr": request.form.get('addr'),
        "endDate": request.form.get('endDate')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_goods, json=data)  # {"retCode":0,"retMsg":"","retData":{"id":"3044"}}
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1
                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            else:  # 发布需求时，retCode!=0 的情况
                return jsonify(
                    {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})
        else:  # 接口请求失败
            return jsonify({"retCode": 90, "retMsg": "请求过程中出现异常", "retData": None})

    except Exception as e:  # 其他异常
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addCars', methods=["get", "post"])
def add_cars():
    data = {
        "openId": request.form.get('openId'),
        "lineData": "[{'from':'南京市','to':'北京市'}]",
        "carNum": request.form.get('carNum'),
        "carModel": "7.6米 公路货车",
        "carryWeight": "10",
        "carryVolume": "40",
        "addr": "上海市青浦区徐德路",
        "lon": 121.265562,
        "lat": 31.192338,
        "endDate": "2018-10-01",
        "contractType": 2,
        "desc": "这里是承运介绍",
        "carImg": "https://wxcx.yunchehome.com/mpw1536216548885.jpg",
        "carPersonImg": "https://wxcx.yunchehome.com/mpw1536216554920.jpg"
    }

    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_cars, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addBusiness', methods=["get", "post"])
def add_business():
    data = {
        "openId": request.form.get('openId'),
        "companyName": request.form.get('companyName'),
        "merchantsTitle": request.form.get('merchantsTitle'),
        "merchantsArea": "[{\"prov\":\"上海市\",\"city\":\"全域\",\"area\":\"全域\"}]",
        "merchantsStartTime": 1546300800,
        "merchantsEndTime": 1551398400,
        "merchantsType": 2,
        "merchantsTypeTwo": 1,
        "merchantsCharge": request.form.get('merchantsCharge'),
        "phone": request.form.get('phone'),
        "addr": "上海市青浦区华徐公路683号",
        "lon": 121.26601,
        "lat": 31.196965,
        "endDate": "2020-10-01",
        "qualRequire": "【招商】自动发布脚本中的补充说明",
        "businessLicenseImg": request.form.get('businessLicenseImg'),
        "chargeCardImg": request.form.get('chargeCardImg'),
        "url": request.form.get('url')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_business, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                # 验证需求详情
                print("验证需求详情！")
                retMsg = ""
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addCarSell', methods=["get", "post"])
def add_carsell():
    data = {
        "openId": request.form.get('openId'),
        "addr": "上海市青浦区华徐公路683号",
        "lon": 121.26601,
        "lat": 31.196965,
        "endDate": "2018-10-10",
        "carSort": request.form.get('carSort'),
        "driveForm": 9,
        "carBrandsId": "39",
        "carSeriesId": "46",
        "maxPower": "300",
        "emissionStand": request.form.get('emissionStand'),
        "drivingLiceDate": "",
        "kilometers": "",
        "shellPrice": request.form.get('shellPrice'),
        "carImg": request.form.get('carImg'),
        "drivingRoomImg": request.form.get('drivingRoomImg'),
        "chassisImg": request.form.get('chassisImg'),
        "desc": request.form.get('desc')
    }
    isInMydemand = 0
    isInRecommand = 0
    isDemandChecked = 0
    try:
        res = requests.post(urls.url_add_carsell, json=data)
        if res.status_code == 200:
            res = json.loads(res.text)
            if res.get('retCode') == 0:
                retData = res['retData']
                demandId = retData.get('id')

                print("验证需求详情！")
                if business.check_demand_info(demandId, data).get("retCode") == 0:
                    isDemandChecked = 1
                else:
                    retMsg = business.check_demand_info(demandId, data).get("retMsg")

                # 验证我的需求
                if business.is_in_mydemand(demandId=demandId):
                    print("验证我的需求！")
                    isInMydemand = 1

                # 验证需求广场
                if business.is_in_recommand(demandId=demandId):
                    print("验证需求广场！")
                    isInRecommand = 1

                return jsonify({"retCode": 0, "retMsg": retMsg,
                                "retData": {"isInMydemand": isInMydemand, "isInRecommand": isInRecommand,
                                            "isDemandChecked": isDemandChecked}})
            return jsonify(
                {"retCode": res.get('retCode'), "retMsg": res.get('retMsg'), "retData": res.get('retData')})

    except Exception as e:
        print(e)
        return jsonify({"retCode": 99, "retMsg": str(e), "retData": None})


@server.route('/demand/addOtherDemand', methods=["get", "post"])
def add_other():
    print("openId:%s" % request.get_json(force=True)['openId'])
    print(request.get_json(force=True)['info']['type'])
    print(type(request.get_json(force=True)['info']))
    data = {
        "openId": request.get_json(force=True)['openId'],
        "info": json.dumps(request.get_json(force=True)['info'])
    }

    # data = {
    #     "openId": request.get_json(force=True)['openId'],
    #     "info": {

front/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
    {# 引入easyui #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    {#  引入自定义的css文件  #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='mycss.css') }}">

    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>
</head>

<body class="easyui-layout">
<div data-options="region:'north',border:false" ;
     style="height: 50px; background: #23d7ea; padding: 10px">
    <img src="{{ url_for('static',filename='images/logo.png') }}" width="100px" height="20px"/> 自动化测试平台
</div>

<div data-options="region:'west',split:true" style="width: 170px;">
    <div class="easyui-accordion" data-options="fit:true,border:false">
        <div title="测试管理" data-options="selected:true">
            <div style="margin: 5px">
                <ul class="tree easyui-tree" data-options="animate:true,lines:true" id="tt">
                    <li data-options="iconCls:'icon-group'">
                        <span>自动化测试</span>
                        <ul>
                            <li data-options="iconCls:'icon-group_add'" id="wx">
                                <span id="ww">小程序</span>
                            </li>
                            <li data-options="iconCls:'icon-group_delete'" id="neway">
                                <span>雷励金科</span>
                            </li>
                            <li data-options="iconCls:'icon-group_edit'" id="finance">
                                <span>业务系统</span>
                            </li>
                            <li data-options="iconCls:'icon-group_edit'" id="all">
                                <span>集成测试</span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        {#        <div title="数据展示" style="padding: 10px;">#}
        {#            content2#}
        {#        </div>#}
    </div>
</div>

<div data-options="region:'center'">
    {# fit：自适应父容器大小   #}
    <div id="tabs" class="easyui-tabs" data-options="tools:'#tab-tools',fit:true">
        <div title="主页" data-options="iconCls:'icon-house'" style="padding: 20px">
            <p>欢迎使用自动化测试平台</p>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $('#tt').tree({

            onClick: function (node) {
                if ($('#tabs').tree('isLeaf', node.target)) { //判断是否是叶子节点
                    {#var tab = $('#tt').tabs('getSelected');#}
                    if ('wx' == node.id) {
                        addTabs(node.text, "{{ url_for('front.suite_wx') }}")
                    } else if ('neway' == node.id) {
                        addTabs(node.text, "{{ url_for('front.suite_neway') }}")
                    } else if ('finance' == node.id) {
                        addTabs(node.text, "{{ url_for('front.suite_finance') }}")
                    } else {
                        addTabs(node.text, "{{ url_for('front.suite_all') }}")
                    }
                }
            }
        })


        //生成新的选项卡
        function addTabs(text, url) {

            //若选项卡已存在，则选中该选项卡
            if ($("#tabs").tabs('exists', text)) {
                $("#tabs").tabs('select', text);
            } else {
                $("#tabs").tabs('add', {
                    title: text,
                    closable: true,
                    href: url,
                });
            }
        }
    })


</script>
</body>
</html>

front/templates/models.html
{% extends "base.html" %}
{% block body %}

    <div id="win_demand" class="easyui-window" title="货源需求"
         style="width:900px;height:700px; padding-left: 10px;padding-top: 10px "
         data-options="modal:true,resizable:false,collapsible:false,minimizable:false,maximizable:false">
        <strong>填写如下信息</strong>
        <div class="easyui-panel"> {# noheader="true" #}
            <form id="form_goods">

                <div style="padding: 10px; ">
                    <label for="goodsName">货物名称:</label>
                    <input class="easyui-textbox" style="width:300px" value="手机" name="goodsName" id="goodsName">

                    <label for="startAddress">装货地址:</label>
                    <input class="easyui-textbox" style="width:300px" value="上海市青浦区华徐公路888号" name="startAddress">
                </div>

                <div style="padding: 10px">
                    <label for="email">卸货地址:</label>
                    <input class="easyui-textbox" style="width:300px" value="北京市海淀区" name="endAddress">
                    <label for="email">装车时间:</label>
                    <input class="easyui-textbox" style="width:300px" value="2018-12-31 11:30"
                           name="carryGoodsTime">
                </div>

                <div style="padding: 10px">
                    <label for="email">货物体积:</label>
                    <input class="easyui-textbox" style="width:300px" value="22" name="carryVolume">
                    <label for="email">车长车型:</label>
                    <input class="easyui-textbox" style="width:300px" value="1.8米 半挂牵引车" name="carModel">
                </div>

                <div style="padding: 10px">
                    <label for="email">发布地点:</label>
                    <input class="easyui-textbox" style="width:300px" value="上海市青浦区双联路88号" name="addr">
                    <label for="email">有效期限:</label>
                    <input class="easyui-textbox" style="width:300px" value="2020-12-15" name="endDate">
                </div>
                {#            <input type="text" hidden="true" value="o94HS5PrLEd6AeyLRM5XimFX90tU" name="openId"/>#}

                <div style="padding: 10px">
                    <span>openId:</span>
                    <select id="cb_openIds" class="easyui-combobox" name="openId" style="width:280px;">
                        <option value="o94HS5PrLEd6AeyLRM5XimFX90tU">o94HS5PrLEd6AeyLRM5XimFX90tU</option>
                        <option value="o94HS5Amxfcwn9pgj-fvByTp70Do">o94HS5Amxfcwn9pgj-fvByTp70Do</option>
                    </select>

                    <a id="btn_publish" class="easyui-linkbutton" style="margin-left: 30px;width: 150px"
                       data-options="iconCls:'icon-add'">点击发布</a>
                </div>
            </form>
        </div>

        <div style="height: 10px"></div>

        <div class="easyui-panel" title="验证点" style="padding: 10px">
            <div class="mdiv" style="padding-top: 10px">
                <span>发布结果：</span>
                <input id="add_result" type="text" readonly=true/>
            </div>
            <div class="mdiv" style="padding-top: 10px">
                <span>验证需求详情：</span>
                <input id="ck_demandinfo" type="text" readonly=true/>
            </div>
            <div class="mdiv" style="padding-top: 10px">
                <span>验证我的需求：</span>
                <input id="ck_mydemand" type="text" readonly=true/>
            </div>
            <div class="mdiv" style="padding-top: 10px">
                <span>验证需求广场：</span>
                <input id="ck_recommand" type="text" readonly=true/>
            </div>
        </div>
    </div>
    </div>


    <script type="text/javascript">
        // 步骤
        $('#tb_detail').datagrid({
            iconCls: 'icon-edit',  //图标
            border: true,  //表格是否显示边框
            columns: [[
                {field: 'id', title: 'ID', width: 50, hidden: false},
                {field: 'testName', title: '步骤名称', width: 100},
                {field: 'element', title: '元素', width: 300},
                {field: 'index', title: '索引', width: 50},
                {field: 'findType', title: '查找方式', width: 100},
                {field: 'operateType', title: '操作方式', width: 80},
                {field: 'checkType', title: '断言方式', width: 100},
                {field: 'checkExp', title: '预期结果', width: 100},
            ]],
            nowrap: false,
            striped: true,  //奇偶行是否使用不同的颜色
            loadMsg: '数据正在努力加载，请稍后...',  //加载数据时显示提示信息
        });

        function formatOper(val, row, index) {
            {#console.log(val)#}
            {#console.log(row.id)#}
            {#console.log(index)#}
            return '<a onclick="suiteDetail(' + row.id + ')" class="easyui-linkbutton" >查看详情</a>';
        }

        function suiteDetail(rowId) {
            $.ajax({
                type: 'post',
                url: "{{ url_for('front.suite_detail') }}",
                data: {"id": rowId},
                dataType: 'json',
                success: function (data) {
                    $('#win').window('open');  // open a window
                    $('#tb_detail').datagrid("loadData", data)
                },
                error: function (data) {
                    alert('请求流程详情失败')
                }
            })
        }

        $('#add_goods').click(function ({}) {
            $('#win_demand').window('open');  // open a window
            currentIndex = 0;
        })

        $('#add_cars').click(function ({}) {
            $('#win_demand').window('open');  // open a window
            currentIndex = 1;
        })

        $('#btn_publish').click(function () {
            $.ajax({
                type: "post",
                url: "{{ url_for('front.add_goods') }}",
                data: $('#form_goods').serialize(),
                dataType: "json",
                async: false,
                success: function (result) {

                    console.log(result)
                    console.debug('result:', result)
                    if (result.retCode == 0) {
                        var succ_msg = "验证通过"
                        var fail_msg = "验证失败"
                        $('#add_result').val(result.retMsg);
                        if (result.retData.isDemandChecked == 1) {
                            $('#ck_demandinfo').val(succ_msg)
                        } else {
                            $('#ck_demandinfo').val(fail_msg)
                        }
                        if (result.retData.isInMydemand == 1) {
                            $('#ck_mydemand').val(succ_msg)
                        } else {
                            $('#ck_mydemand').val(fail_msg)
                        }
                        if (result.retData.isInRecommand == 1) {
                            $('#ck_recommand').val(succ_msg)
                        } else {
                            $('#ck_recommand').val(fail_msg)
                        }
                    } else {
                        $('#add_result').val(result.retMsg)
                    }
                },
                error: function (data, type, err) {
                    console.log("ajax错误类型：" + type);
                    console.log(err);
                    alert("发布过程中出现异常,前往控制台查看错误信息！")
                }
            })
        })


        function isRealNum(val) {
            // isNaN()函数 把空串 空格 以及NUll 按照0来处理 所以先去除
            if (val === "" || val == null) {
                return false;
            }
            if (!isNaN(val)) {
                return true;
            } else {
                return false;
            }
        }

    </script>

{% endblock %}

front/templates/new_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/default/easyui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/themes/icon.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='easyui/demo/demo.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='easyui/jquery.easyui.min.js') }}"></script>
</head>
<body>

<div class="easyui-panel" title="发布文章" style="width:100%;max-width:400px;padding:30px 60px;">


    <form id="ff" method="post" ,action="{{ url_for('front.new_article') }}">

        <div style="margin-bottom:20px">
            <input name="title" type="text" style="width:100%;height: 25px" placeholder="请填写文章标题">
        </div>

        <div style="margin-bottom:20px">
            <input name="content" type="text" style="width:100%;height: 25px" placeholder="请填写文章内容">
        </div>
        <div style="margin-bottom:20px">
            <input class="easyui-linkbutton" value="立即发布" type="submit" style="width:80px"></input>
        </div>

    </form>

</div>

</body>
</html>